require_relative('models/customer')
require_relative('models/film')
require_relative('models/ticket')
require('pry-byebug')

Customer.delete_all()
Film.delete_all()
Ticket.delete_all()

customer1 = Customer.new({'name' => 'Bob', 'funds' => '50'})
customer1.save()
customer2 = Customer.new({'name' => 'Jane', 'funds' => '100'})
customer2.save()
customer3 = Customer.new({'name' => 'Sam', 'funds' => '70'})
customer3.save()

film1 = Film.new({'title' => 'Harry Potter', 'price' => '15'})
film1.save()
film2 = Film.new({'title' => 'Fantastic Beasts', 'price' => '20'})
film2.save()
film3 = Film.new({'title' => 'Spider-man', 'price' => '18'})
film3.save()
film4 = Film.new({'title' => 'Hunger Games', 'price' => '12'})
film4.save()
film5 = Film.new({'title' => 'Thor', 'price' => '15'})
film5.save()

ticket1 = Ticket.new({'customer_id' => customer1.id, 'film_id' => film4.id})
ticket1.save()
ticket2 = Ticket.new({'customer_id' => customer2.id, 'film_id' => film2.id})
ticket2.save()
ticket3 = Ticket.new({'customer_id' => customer3.id, 'film_id' => film1.id})
ticket3.save()
ticket4 = Ticket.new({'customer_id' => customer2.id, 'film_id' => film3.id})
ticket4.save()
ticket5 = Ticket.new({'customer_id' => customer3.id, 'film_id' => film3.id})
ticket5.save()

binding.pry
nil
